spring.datasource.url=jdbc:mysql://localhost:3306/bookstore_db
spring.datasource.username=root
# Put your EXACT MySQL password here
spring.datasource.password=babyreddy@09
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver